<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ja" sourcelanguage="en">
  <context>
    <name>AddonsInstaller</name>
    <message>
      <location filename="install_to_toolbar.py" line="76"/>
      <source>Create new toolbar</source>
      <translation type="unfinished">Create new toolbar</translation>
    </message>
    <message>
      <location filename="install_to_toolbar.py" line="219"/>
      <source>A macro installed with the FreeCAD Addon Manager</source>
      <translation type="unfinished">A macro installed with the FreeCAD Addon Manager</translation>
    </message>
    <message>
      <location filename="install_to_toolbar.py" line="221"/>
      <source>Run</source>
      <comment>Indicates a macro that can be &apos;run&apos;</comment>
      <translation>実行</translation>
    </message>
    <message>
      <location filename="package_details.py" line="112"/>
      <source>Version {version} installed on {date}</source>
      <translation> {date} にバージョン {version} がインストールされました</translation>
    </message>
    <message>
      <location filename="package_details.py" line="117"/>
      <source>Version {version} installed</source>
      <translation>バージョン {version} がインストールされました</translation>
    </message>
    <message>
      <location filename="package_details.py" line="121"/>
      <source>Installed on {date}</source>
      <translation>{date} にインストールされました</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="567"/>
      <source>Installed</source>
      <translation>インストール済み</translation>
    </message>
    <message>
      <location filename="package_details.py" line="96"/>
      <source>Version</source>
      <translation>バージョン</translation>
    </message>
    <message>
      <location filename="package_details.py" line="103"/>
      <source>Unknown version (no package.xml file found)</source>
      <translation>不明なバージョン (package.xml ファイルが見つかりません)</translation>
    </message>
    <message>
      <location filename="package_details.py" line="108"/>
      <source>installed on</source>
      <translation>インストール日:</translation>
    </message>
    <message>
      <location filename="package_details.py" line="118"/>
      <source>installed</source>
      <translation>インストール済み</translation>
    </message>
    <message>
      <location filename="package_details.py" line="126"/>
      <source>Update available to version</source>
      <translation>最新バージョンが利用可能です</translation>
    </message>
    <message>
      <location filename="package_details.py" line="144"/>
      <source>This is the latest version available</source>
      <translation>お使いのバージョンは最新です。</translation>
    </message>
    <message>
      <location filename="package_details.py" line="151"/>
      <source>Updated, please restart FreeCAD to use</source>
      <translation>アップデートが完了しました。FreeCADを再起動してください</translation>
    </message>
    <message>
      <location filename="package_details.py" line="159"/>
      <source>Update check in progress</source>
      <translation>アップデート確認中</translation>
    </message>
    <message>
      <location filename="package_details.py" line="163"/>
      <source>Automatic update checks disabled</source>
      <translation>自動でのアップデート確認は無効です</translation>
    </message>
    <message>
      <location filename="package_details.py" line="172"/>
      <source>Installation location</source>
      <translation>インストール場所</translation>
    </message>
    <message>
      <location filename="package_details.py" line="240"/>
      <source>WARNING: This addon is obsolete</source>
      <translation>警告: このアドオンは古いバージョンです</translation>
    </message>
    <message>
      <location filename="package_details.py" line="250"/>
      <source>WARNING: This addon is Python 2 Only</source>
      <translation>警告: このアドオンは Python 2 のみです。</translation>
    </message>
    <message>
      <location filename="package_details.py" line="312"/>
      <source>Fetching README.md from package repository</source>
      <translation>パッケージリポジトリから README.md をフェッチしています</translation>
    </message>
    <message>
      <location filename="package_details.py" line="354"/>
      <source>WARNING: This addon requires FreeCAD </source>
      <translation>警告: このアドオンはFreeCADが必要です </translation>
    </message>
    <message numerus="yes">
      <location filename="package_details.py" line="431"/>
      <source>Delete cached version of this README and re-download</source>
      <translation>
        <numerusform>キャッシュされた、READMEファイルの削除と再ダウンロード</numerusform>
      </translation>
    </message>
    <message>
      <location filename="package_details.py" line="563"/>
      <source>Could not load README data from URL {}</source>
      <translation>URL {} から README データを読み込めませんでした</translation>
    </message>
    <message>
      <location filename="package_details.py" line="577"/>
      <source>Success</source>
      <translation>成功</translation>
    </message>
    <message>
      <location filename="package_details.py" line="600"/>
      <source>Changed to git ref &apos;{}&apos; -- please restart to use Addon.</source>
      <translation>git ref &apos;{} に変更されました&apos; -- Addonを使用するには再起動してください。</translation>
    </message>
    <message>
      <location filename="package_details.py" line="636"/>
      <source>Page JavaScript reported</source>
      <translation>JavaScriptページが報告されました</translation>
    </message>
    <message>
      <location filename="package_details.py" line="407"/>
      <source>Install</source>
      <translation>インストール</translation>
    </message>
    <message>
      <location filename="package_details.py" line="410"/>
      <source>Uninstall</source>
      <translation>アンインストール·</translation>
    </message>
    <message>
      <location filename="package_details.py" line="413"/>
      <source>Update</source>
      <translation>更新</translation>
    </message>
    <message>
      <location filename="package_details.py" line="416"/>
      <source>Check for Update</source>
      <translation>アップデートの確認</translation>
    </message>
    <message>
      <location filename="package_details.py" line="419"/>
      <source>Run Macro</source>
      <translation>マクロの実行</translation>
    </message>
    <message>
      <location filename="package_details.py" line="786"/>
      <source>Change Branch</source>
      <translation>ブランチの変更</translation>
    </message>
    <message>
      <location filename="package_details.py" line="867"/>
      <source>Enable</source>
      <translation>有効</translation>
    </message>
    <message>
      <location filename="package_details.py" line="870"/>
      <source>Disable</source>
      <translation>無効化</translation>
    </message>
    <message>
      <location filename="package_details.py" line="424"/>
      <source>Return to package list</source>
      <translation>パッケージ一覧に戻る</translation>
    </message>
    <message numerus="yes">
      <location filename="package_details.py" line="800"/>
      <source>QtWebEngine Python bindings not installed -- using fallback README display. See Report View for details and installation instructions.</source>
      <translation>
        <numerusform>QtWebEngine Python バインディングがインストールされていません --代替のREADME表示を使用しています。詳細とインストール手順については、レポートビューを参照してください。</numerusform>
      </translation>
    </message>
    <message>
      <location filename="package_list.py" line="119"/>
      <source>Filter is valid</source>
      <translation>フィルタは有効です</translation>
    </message>
    <message>
      <location filename="package_list.py" line="125"/>
      <source>Filter regular expression is invalid</source>
      <translation>フィルタ正規表現が無効です</translation>
    </message>
    <message>
      <location filename="package_list.py" line="207"/>
      <source>Click for details about package {}</source>
      <translation>パッケージの詳細についてはクリックしてください {}</translation>
    </message>
    <message>
      <location filename="package_list.py" line="211"/>
      <source>Click for details about workbench {}</source>
      <translation>クリックしてワークベンチ{} の詳細を確認する</translation>
    </message>
    <message>
      <location filename="package_list.py" line="215"/>
      <source>Click for details about macro {}</source>
      <translation>マクロの詳細については {} をクリックしてください</translation>
    </message>
    <message>
      <location filename="package_list.py" line="326"/>
      <source>Maintainer</source>
      <translation>メンテナー</translation>
    </message>
    <message>
      <location filename="package_list.py" line="330"/>
      <source>Maintainers:</source>
      <translation>メンテナー:</translation>
    </message>
    <message>
      <location filename="package_list.py" line="364"/>
      <source>Tags</source>
      <translation>タグ</translation>
    </message>
    <message>
      <location filename="package_list.py" line="371"/>
      <source>updated</source>
      <translation>更新</translation>
    </message>
    <message>
      <location filename="package_list.py" line="382"/>
      <source>Author</source>
      <translation>作成者</translation>
    </message>
    <message>
      <location filename="package_list.py" line="404"/>
      <source>Up-to-date</source>
      <translation>最新版</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="586"/>
      <source>Update available</source>
      <translation>アップデートを利用できます</translation>
    </message>
    <message>
      <location filename="package_list.py" line="414"/>
      <source>Pending restart</source>
      <translation>再起動を保留中</translation>
    </message>
    <message>
      <location filename="package_list.py" line="498"/>
      <source>DISABLED</source>
      <translation type="unfinished">DISABLED</translation>
    </message>
    <message>
      <location filename="package_list.py" line="372"/>
      <source>Installed version</source>
      <translation>インストール済のバージョン</translation>
    </message>
    <message>
      <location filename="package_list.py" line="180"/>
      <source>Click for details about package</source>
      <translation>クリックしてパッケージの詳細を見る</translation>
    </message>
    <message>
      <location filename="package_list.py" line="185"/>
      <source>Click for details about workbench</source>
      <translation>クリックしてワークベンチの詳細を見る</translation>
    </message>
    <message>
      <location filename="package_list.py" line="190"/>
      <source>Click for details about macro</source>
      <translation>クリックしてマクロの詳細を見る</translation>
    </message>
    <message>
      <location filename="package_list.py" line="376"/>
      <source>Updated</source>
      <translation>更新完了</translation>
    </message>
    <message>
      <location filename="package_list.py" line="380"/>
      <source>Unknown version</source>
      <translation>不明なバージョン</translation>
    </message>
    <message>
      <location filename="package_list.py" line="383"/>
      <source>Installed on</source>
      <translation>インストール済み:</translation>
    </message>
    <message>
      <location filename="package_list.py" line="394"/>
      <source>Available version</source>
      <translation>利用可能なバージョン</translation>
    </message>
    <message>
      <location filename="package_list.py" line="566"/>
      <source>Show Addons containing:</source>
      <translation>アドオンに含まれるものを表示</translation>
    </message>
    <message>
      <location filename="package_list.py" line="569"/>
      <source>All</source>
      <translation>すべて</translation>
    </message>
    <message>
      <location filename="package_list.py" line="572"/>
      <source>Workbenches</source>
      <translation>ワークベンチ</translation>
    </message>
    <message>
      <location filename="package_list.py" line="575"/>
      <source>Macros</source>
      <translation>マクロ</translation>
    </message>
    <message>
      <location filename="package_list.py" line="578"/>
      <source>Preference Packs</source>
      <translation>プリファレンスパック</translation>
    </message>
    <message>
      <location filename="package_list.py" line="692"/>
      <source>Status:</source>
      <translation>ステータス:</translation>
    </message>
    <message>
      <location filename="package_list.py" line="695"/>
      <source>Any</source>
      <translation>任意</translation>
    </message>
    <message>
      <location filename="package_list.py" line="702"/>
      <source>Not installed</source>
      <translation>未インストール</translation>
    </message>
    <message>
      <location filename="package_list.py" line="582"/>
      <source>Filter</source>
      <translation>フィルター</translation>
    </message>
    <message>
      <location filename="package_list.py" line="585"/>
      <source>OK</source>
      <translation>OK</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="115"/>
      <source>Checking network connection...
</source>
      <translation>ネットワーク接続を確認中...
</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="167"/>
      <source>Unable to download addon list.</source>
      <translation>アドオンの一覧をダウンロードできませんでした。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="172"/>
      <source>Workbenches list was updated.</source>
      <translation>ワークベンチの一覧を更新しました。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="261"/>
      <source>Failed loading</source>
      <translation>読み込みに失敗しました</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="296"/>
      <source>List of macros successfully retrieved.</source>
      <translation>マクロの一覧を取り込むことに成功しました。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="310"/>
      <source>GitPython not installed! Cannot retrieve macros from git</source>
      <translation>GitPythonがインストールされていませんでした！よってマクロをgitより取り戻すことができません</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="319"/>
      <source>Something went wrong with the Git Macro Retrieval, possibly the Git executable is not in the path</source>
      <translation>Git マクロの取得に問題が発生しました。おそらく Git 実行ファイルがパス中にありません。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="343"/>
      <source>Appears to be an issue connecting to the Wiki, therefore cannot retrieve Wiki macro list at this time</source>
      <translation>Wikiへの接続で問題が発生したため、現時点ではWikiのマクロリストを取得できません。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="367"/>
      <source>Unable to fetch git updates for workbench</source>
      <translation>ワークベンチのGitアップデートを取得できません</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="391"/>
      <source>Retrieving info from</source>
      <translation>情報を取り込み中</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="419"/>
      <source>Failed to read metadata from</source>
      <translation>メタデータの読み込みに失敗しました</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="426"/>
      <source>git fetch failed for {}</source>
      <translation>{} の git フェッチに失敗しました</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="429"/>
      <source>git fetch failed for {wb.name}</source>
      <translation>{wb.name} の git フェッチに失敗しました</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="433"/>
      <source>Raw markdown displayed</source>
      <translation>未加工のマークダウンを表示</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="435"/>
      <source>Python Markdown library is missing.</source>
      <translation>Python Markdown ライブラリがありません。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="439"/>
      <source>git pull failed for {wb.name}</source>
      <translation>{wb.name} の git プルに失敗しました</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="514"/>
      <source>Done locating macros.</source>
      <translation>マクロの配置を完了しました。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="521"/>
      <source>This addon is already installed.</source>
      <translation>このアドオンは既にインストールされています。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="533"/>
      <source>An update is available for this addon.</source>
      <translation>このアドオンでアップデートが利用可能です。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="547"/>
      <source>This addon is marked as obsolete</source>
      <translation>このアドオンは非推奨に設定されています</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="551"/>
      <source>This usually means it is no longer maintained, and some more advanced addon in this list provides the same functionality.</source>
      <translation>通常はすでにメンテナンスがされていないことを意味します。このリストにあるさらに高度なアドオンが同じ機能を提供している場合があります。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="559"/>
      <source>This addon is marked as Python 2 Only</source>
      <translation>このアドオンは Python 2 専用として記されています</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="564"/>
      <source>This workbench may no longer be maintained and installing it on a Python 3 system will more than likely result in errors at startup or while in use.</source>
      <translation>このワークベンチは保守されておらず、Python 3 システムにインストールすると起動時や使用中にエラーが発生する可能性が高くなります。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="608"/>
      <source>An error occurred fetching macros from GitHub</source>
      <translation>GitHubからマクロを取得中にエラーが発生しました</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="646"/>
      <source>An error occurred updating macros from GitHub</source>
      <translation type="unfinished">An error occurred updating macros from GitHub</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="651"/>
      <source>Retrieving description...</source>
      <translation>説明の取り込み中</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="665"/>
      <source>This macro is already installed.</source>
      <translation>このマクロは既にインストールされています。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="697"/>
      <source>Caching macro code...</source>
      <translation>マクロコードをキャッシュ中...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="700"/>
      <source>GitPython not found. Using standard download instead.</source>
      <translation>GitPythonが見つかりません。代わりに標準のダウンロードを使用しています。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="705"/>
      <source>Your version of python doesn&apos;t appear to support ZIP files. Unable to proceed.</source>
      <translation>利用しているPythonのバージョンではZIPファイルをサポートしていないようです。ゆえに続行できません。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="727"/>
      <source>User requested updating a Python 2 workbench on a system running Python 3 - </source>
      <translation>ユーザーが Python 3 を実行しているシステムで Python 2 用ワークベンチの更新を要求しました - </translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="738"/>
      <source>Outdated GitPython detected, consider upgrading with pip.</source>
      <translation>古い GitPython が見つかりました。pip によるアップグレードを検討してください。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="763"/>
      <source>Workbench successfully updated. Please restart FreeCAD to apply the changes.</source>
      <translation>ワークベンチの更新が成功しました。 FreeCADを再起動して変更を有効にしてください。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="771"/>
      <source>User requested installing a Python 2 workbench on a system running Python 3 - </source>
      <translation>ユーザーが Python 3 を実行しているシステムで Python 2 用ワークベンチのインストールを要求しました - </translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="786"/>
      <source>Workbench successfully installed. Please restart FreeCAD to apply the changes.</source>
      <translation>ワークベンチのインストールが成功しました。 FreeCADを再起動して変更を有効にしてください。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="799"/>
      <source>A macro has been installed and is available under Macro -&gt; Macros menu</source>
      <translation>マクロがインストールされました。メニューのマクロ -&gt; マクロから利用できます。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="824"/>
      <source>Retrieving info from {}</source>
      <translation>{} から情報を取得しています</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="835"/>
      <source>Missing workbench</source>
      <translation>ワークベンチが見当たりません</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="844"/>
      <source>Missing python module</source>
      <translation>Pythonが見当たりません</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="854"/>
      <source>Missing optional python module (doesn&apos;t prevent installing)</source>
      <translation>オプションのPythonモジュールが見つかりません(インストールは停止されません)</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="857"/>
      <source>Some errors were found that prevent to install this workbench</source>
      <translation>エラーが発生したためこのワークベンチをインストールすることができません</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="859"/>
      <source>Please install the missing components first.</source>
      <translation>先ずは、見当たらないコンポーネントをインストールしてください。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="915"/>
      <source>Retrieving macro description...</source>
      <translation>マクロの説明を取得しています...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="653"/>
      <source>Retrieving info from git</source>
      <translation>Gitからの情報を取り込み中</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="873"/>
      <source>Error: Unable to locate zip from</source>
      <translation>エラー: ZIP ファイルを以下から配置できません。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="656"/>
      <source>Retrieving info from wiki</source>
      <translation>Wikiからの情報を取得しています</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="880"/>
      <source>Error: Unable to download</source>
      <translation>エラー: ダウンロードできませんでした</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="893"/>
      <source>Successfully installed</source>
      <translation>インストールが完了しました</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1013"/>
      <source>Error updating module</source>
      <translation type="unfinished">Error updating module</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1078"/>
      <source>Please fix manually</source>
      <translation>手動で修正してください</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1075"/>
      <source>Error updating module </source>
      <translation>モジュールの更新に失敗しました </translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1220"/>
      <source>Error: Unable to locate ZIP from</source>
      <translation>エラー: ZIP ファイルを配置できません。</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1403"/>
      <source>Retrieving package metadata...</source>
      <translation>パッケージのメタデータを取得しています...</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1405"/>
      <source>Failed to execute pip. Returned error was:</source>
      <translation>pipの実行に失敗しました。エラーが返されました:</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1611"/>
      <source>Downloaded package.xml for {}</source>
      <translation>{} の package.xml をダウンロードしました</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1641"/>
      <source>Downloaded metadata.txt for {}</source>
      <translation>{} の metadata.txt をダウンロードしました</translation>
    </message>
    <message>
      <location filename="addonmanager_workers.py" line="1715"/>
      <source>Downloaded icon for {}</source>
      <translation>{} のダウンロードされたアイコン</translation>
    </message>
    <message>
      <location filename="addonmanager_utilities.py" line="332"/>
      <source>Failed to repair missing .git directory</source>
      <translation>.git ディレクトリの不足を修復できませんでした</translation>
    </message>
    <message>
      <location filename="addonmanager_utilities.py" line="335"/>
      <source>Repository URL</source>
      <translation>リポジトリURL</translation>
    </message>
    <message>
      <location filename="addonmanager_utilities.py" line="338"/>
      <source>Clone directory</source>
      <translation>ディレクトリを複製</translation>
    </message>
    <message>
      <location filename="addonmanager_metadata.py" line="72"/>
      <source>Error with encrypted connection</source>
      <translation>暗号化された接続でエラー</translation>
    </message>
    <message>
      <location filename="addonmanager_metadata.py" line="135"/>
      <source>Failed to connect to</source>
      <translation>接続に失敗しました</translation>
    </message>
    <message>
      <location filename="addonmanager_metadata.py" line="220"/>
      <source>Failed to connect to URL</source>
      <translation>URLへの接続に失敗しました</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="101"/>
      <source>DANGER: Developer feature</source>
      <translation>危険: 開発者機能</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="114"/>
      <source>There are local changes</source>
      <translation>ローカルの変更があります</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="192"/>
      <source>Branch</source>
      <comment>git terminology</comment>
      <translation>ブランチ</translation>
    </message>
    <message>
      <location filename="change_branch.py" line="178"/>
      <source>Tag</source>
      <comment>git terminology</comment>
      <translation type="unfinished">Tag</translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="261"/>
      <source>Kind</source>
      <comment>Table header for git ref type (e.g. either Tag or Branch)</comment>
      <translation>
        <numerusform>種類</numerusform>
      </translation>
    </message>
    <message>
      <location filename="change_branch.py" line="265"/>
      <source>Local name</source>
      <comment>Table header for git ref name</comment>
      <translation>ローカル名</translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="271"/>
      <source>Tracking</source>
      <comment>Table header for git remote tracking branch name name</comment>
      <translation>
        <numerusform>トラッキング</numerusform>
      </translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="277"/>
      <source>Local updated</source>
      <comment>Table header for git update time of local branch</comment>
      <translation>
        <numerusform>ローカルが更新されました</numerusform>
      </translation>
    </message>
    <message numerus="yes">
      <location filename="change_branch.py" line="283"/>
      <source>Remote updated</source>
      <comment>Table header for git update time of remote branch</comment>
      <translation>
        <numerusform>リモートが更新されました</numerusform>
      </translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="191"/>
      <source>Checking connection</source>
      <translation>接続の確認中</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="192"/>
      <source>Checking for connection to GitHub...</source>
      <translation>GitHub への接続を確認しています...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="213"/>
      <source>Connection failed</source>
      <translation>接続に失敗しました</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="240"/>
      <source>Missing dependency</source>
      <translation>依存関係がありません</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="324"/>
      <source>Starting up...</source>
      <translation>起動中...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="258"/>
      <source>Loading addon information</source>
      <translation>アドオン情報を読み込み中</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="199"/>
      <source>Addon manager</source>
      <translation>アドオンマネージャー</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="209"/>
      <source>Restart now</source>
      <translation>今すぐ再起動</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="210"/>
      <source>Restart later</source>
      <translation>後で再起動する</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1248"/>
      <source>Refresh local cache</source>
      <translation>ローカルキャッシュを更新</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="659"/>
      <source>Updating cache...</source>
      <translation>キャッシュを更新しています...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="243"/>
      <source>Checking for updates...</source>
      <translation>アップデートを確認中…</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="773"/>
      <source>Apply {} update(s)</source>
      <translation>{} アップデートを適用</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="86"/>
      <source>The addons that can be installed here are not officially part of FreeCAD, and are not reviewed by the FreeCAD team. Make sure you know what you are installing!</source>
      <translation>ここからインストールできますアドオンは、FreeCAD公式の一部ではないゆえにFreeCADチームによってレビューがなされていない。あなたが何をインストールしようとしているかを確認して下さい！</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="203"/>
      <source>You must restart FreeCAD for changes to take effect.</source>
      <translation>変更を有効にするにはFreeCADを再起動する必要があります。</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="204"/>
      <source>You must restart FreeCAD for changes to take effect. Press Ok to restart FreeCAD now, or Cancel to restart later.</source>
      <translation>変更を反映するにはFreeCADを再起動する必要があります。今すぐFreeCADを再起動する場合はOKを、後で再起動する場合はキャンセルを押してください。</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="241"/>
      <source>Could not import QtNetwork -- see Report View for details. Addon Manager unavailable.</source>
      <translation>QtNetworkをインポートできませんでした。詳細についてはレポートビューを参照してください。アドオンマネージャーは利用できません。</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="262"/>
      <source>Apply</source>
      <translation>適用する</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="263"/>
      <source>update(s)</source>
      <translation>アップデート</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="266"/>
      <source>No update available</source>
      <translation>利用可能なアップデートはありません</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="433"/>
      <source>Macro successfully installed. The macro is now available from the Macros dialog.</source>
      <translation>マクロのインストールが成功しました。このマクロは、マクロダイアログよりすぐに利用できます。</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="435"/>
      <source>Unable to install</source>
      <translation>インストールできません</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="494"/>
      <source>Addon successfully removed. Please restart FreeCAD</source>
      <translation>アドオンの削除が成功しました。FreeCADを再起動してください。</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="496"/>
      <source>Unable to remove this addon</source>
      <translation>このアドオンを削除できません</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="502"/>
      <source>Macro successfully removed.</source>
      <translation>マクロを削除しました</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="504"/>
      <source>Macro could not be removed.</source>
      <translation>マクロを削除できませんでした</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="534"/>
      <source>Addon Manager: Skipping update check because AutoCheck user preference is False</source>
      <translation>Addon Manager: AutoCheck ユーザー設定が False であるため、更新チェックをスキップします</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="542"/>
      <source>Restart required</source>
      <translation>再起動が必要です</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="577"/>
      <source>No updates available</source>
      <translation>利用可能なアップデートはありません</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="774"/>
      <source>All packages updates failed. Packages:</source>
      <translation>すべてのパッケージの更新に失敗しました。 パッケージ:</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="786"/>
      <source>Failed packages:</source>
      <translation>失敗したパッケージ:</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="915"/>
      <source>Too many to list</source>
      <translation>リストするには多すぎます</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="893"/>
      <source>Missing Requirement</source>
      <translation>不足している要件</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="964"/>
      <source>Installing dependencies</source>
      <translation>依存関係インストール中</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1061"/>
      <source>Cannot execute Python</source>
      <translation>Pythonを実行できません</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1081"/>
      <source>Cannot execute pip</source>
      <translation>pipを実行できません</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1102"/>
      <source>Package installation failed</source>
      <translation>パッケージのインストールに失敗しました</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1105"/>
      <source>See Report View for detailed failure log.</source>
      <translation>詳細な失敗ログについては、レポートビューを参照してください。</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="703"/>
      <source>Installation of macro failed</source>
      <translation>マクロのインストールに失敗しました</translation>
    </message>
    <message numerus="yes">
      <location filename="AddonManager.py" line="1280"/>
      <source>{} total, see Report view for list</source>
      <comment>Describes the number of updates that were completed (&apos;{}&apos; is replaced by the number of updates)</comment>
      <translation>
        <numerusform>計 {} リストのレポートビューを参照してください</numerusform>
      </translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1178"/>
      <source>Succeeded</source>
      <translation>正常終了</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1159"/>
      <source>All packages updates failed:</source>
      <translation>すべてのパッケージの更新に失敗しました:</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1183"/>
      <source>Failed</source>
      <translation>失敗</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="800"/>
      <source>Update report</source>
      <translation>レポートを更新</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="850"/>
      <source>Installation succeeded</source>
      <translation>インストールに成功しました</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="866"/>
      <source>Installation failed</source>
      <translation>インストールに失敗しました。</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1457"/>
      <source>Confirm remove</source>
      <translation>削除を確認</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1460"/>
      <source>Are you sure you want to uninstall this Addon?</source>
      <translation>本当にこのアドオンを削除しますか？</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1513"/>
      <source>Execution of Addon&apos;s uninstall.py script failed. Proceeding with uninstall...</source>
      <translation>Addon&apos;s uninstall.py スクリプトの実行に失敗しました。アンインストールして続行します...</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="1558"/>
      <source>Successfully uninstalled {}</source>
      <translation type="unfinished">Successfully uninstalled {}</translation>
    </message>
    <message>
      <location filename="addonmanager_macro.py" line="157"/>
      <source>Unable to fetch the code of this macro.</source>
      <translation>このマクロのコードがフェッチできません。</translation>
    </message>
    <message>
      <location filename="addonmanager_macro.py" line="164"/>
      <source>Unable to retrieve a description for this macro.</source>
      <translation>このマクロについての説明を受信することができません。</translation>
    </message>
  </context>
  <context>
    <name>Std_AddonMgr</name>
    <message>
      <location filename="AddonManager.py" line="68"/>
      <source>&amp;Addon manager</source>
      <translation>アドオンマネージャー(&amp;A)</translation>
    </message>
    <message>
      <location filename="AddonManager.py" line="69"/>
      <source>Manage external workbenches and macros</source>
      <translation>外部のワークベンチとマクロを管理</translation>
    </message>
  </context>
  <context>
    <name>AddonInstaller</name>
    <message>
      <location filename="addonmanager_workers.py" line="535"/>
      <source>Installed location</source>
      <translation>インストール場所</translation>
    </message>
  </context>
  <context>
    <name>Dialog</name>
    <message>
      <location filename="../../AddonManager.ui" line="14"/>
      <source>Addon Manager</source>
      <translation>アドオン・マネージャー</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="37"/>
      <source>Workbenches</source>
      <translation>ワークベンチ</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="47"/>
      <source>Macros</source>
      <translation>マクロ</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="56"/>
      <source>Executes the selected macro, if installed</source>
      <translation>インストールされている場合、選択したマクロを実行</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="59"/>
      <source>Execute</source>
      <translation>実行</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="89"/>
      <source>Sets configuration options for the Addon Manager</source>
      <translation>アドオン・マネージャーの構成オプションを設定</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="92"/>
      <source>Configure...</source>
      <translation>設定...</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="113"/>
      <source>Downloading info...</source>
      <translation>ダウンロード情報....</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="127"/>
      <source>Uninstalls a selected macro or workbench</source>
      <translation>選択したマクロ、ワークベンチをアンインストール</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="130"/>
      <source>Uninstall selected</source>
      <translation>選択したものをアンインストール</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="137"/>
      <source>Installs or updates the selected macro or workbench</source>
      <translation>選択したマクロ、ワークベンチをインストールまたは更新</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="140"/>
      <source>Install/update selected</source>
      <translation>選択したものをインストール/更新</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="147"/>
      <source>Download and apply all available updates</source>
      <translation>利用可能な全てのアップデートをダウンロードして適用する</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="150"/>
      <source>Update all</source>
      <translation>すべて更新</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="157"/>
      <source>Close the Addon Manager</source>
      <translation>アドオン・マネージャーを閉じる</translation>
    </message>
    <message>
      <location filename="../../AddonManager.ui" line="160"/>
      <source>Close</source>
      <translation>閉じる</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="14"/>
      <source>Addon manager options</source>
      <translation>アドオン・マネージャーのオプション</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="20"/>
      <source>If this option is selected, when launching the Addon Manager,
installed addons will be checked for available updates
(this requires the GitPython package installed on your system)</source>
      <translation>このオプションが選択されている場合、アドオン・マネージャーの起動時にインストールされているアドオンに利用可能な更新があるかがチェックされます（システムにGitPythonパッケージがインストールされている必要があります）</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="25"/>
      <source>Automatically check for updates at start (requires GitPython)</source>
      <translation>開始時に更新を自動確認 （GitPython が必要）</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="35"/>
      <source>Custom repositories (one per line):</source>
      <translation>カスタム・レポジトリー（1行に1つ）:</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="42"/>
      <source>You can use this window to specify additional addon repositories
to be scanned for available addons</source>
      <translation>このウィンドウを使用して、利用可能なアドオンをスキャンさせる追加のアドオン・レポジトリーを指定できます</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="57"/>
      <source>Proxy </source>
      <translation>プロキシ </translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="64"/>
      <source>No proxy</source>
      <translation>プロキシを使用しない</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="71"/>
      <source>User system proxy</source>
      <translation>ユーザーシステムプロキシ</translation>
    </message>
    <message>
      <location filename="../../AddonManagerOptions.ui" line="78"/>
      <source>User defined proxy :</source>
      <translation>ユーザー定義プロキシ:</translation>
    </message>
  </context>
</TS>
